name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5.4.0
        with:
          go-version: '1.24'
      - name: Run coverage
        run:  go test -coverpkg=./... ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          verbose: true 
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
